package com.castiel.model.generator;

import com.castiel.core.base.BaseModel;

@SuppressWarnings("serial")
public class PBasicDept extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_dept.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_dept.DEPT_NO
     *
     * @mbggenerated
     */
    private String deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_dept.DEPT_ADDRESS
     *
     * @mbggenerated
     */
    private String deptAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_dept.DEPT_MANAGE
     *
     * @mbggenerated
     */
    private String deptManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_dept.DEPT_PHONE
     *
     * @mbggenerated
     */
    private String deptPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_dept.DEPT_NAME
     *
     * @return the value of p_basic_dept.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_dept.DEPT_NAME
     *
     * @param deptName the value for p_basic_dept.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_dept.DEPT_NO
     *
     * @return the value of p_basic_dept.DEPT_NO
     *
     * @mbggenerated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_dept.DEPT_NO
     *
     * @param deptNo the value for p_basic_dept.DEPT_NO
     *
     * @mbggenerated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_dept.DEPT_ADDRESS
     *
     * @return the value of p_basic_dept.DEPT_ADDRESS
     *
     * @mbggenerated
     */
    public String getDeptAddress() {
        return deptAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_dept.DEPT_ADDRESS
     *
     * @param deptAddress the value for p_basic_dept.DEPT_ADDRESS
     *
     * @mbggenerated
     */
    public void setDeptAddress(String deptAddress) {
        this.deptAddress = deptAddress == null ? null : deptAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_dept.DEPT_MANAGE
     *
     * @return the value of p_basic_dept.DEPT_MANAGE
     *
     * @mbggenerated
     */
    public String getDeptManage() {
        return deptManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_dept.DEPT_MANAGE
     *
     * @param deptManage the value for p_basic_dept.DEPT_MANAGE
     *
     * @mbggenerated
     */
    public void setDeptManage(String deptManage) {
        this.deptManage = deptManage == null ? null : deptManage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_dept.DEPT_PHONE
     *
     * @return the value of p_basic_dept.DEPT_PHONE
     *
     * @mbggenerated
     */
    public String getDeptPhone() {
        return deptPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_dept.DEPT_PHONE
     *
     * @param deptPhone the value for p_basic_dept.DEPT_PHONE
     *
     * @mbggenerated
     */
    public void setDeptPhone(String deptPhone) {
        this.deptPhone = deptPhone == null ? null : deptPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_basic_dept
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deptName=").append(deptName);
        sb.append(", deptNo=").append(deptNo);
        sb.append(", deptAddress=").append(deptAddress);
        sb.append(", deptManage=").append(deptManage);
        sb.append(", deptPhone=").append(deptPhone);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_basic_dept
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PBasicDept other = (PBasicDept) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDeptName() == null ? other.getDeptName() == null : this.getDeptName().equals(other.getDeptName()))
            && (this.getDeptNo() == null ? other.getDeptNo() == null : this.getDeptNo().equals(other.getDeptNo()))
            && (this.getDeptAddress() == null ? other.getDeptAddress() == null : this.getDeptAddress().equals(other.getDeptAddress()))
            && (this.getDeptManage() == null ? other.getDeptManage() == null : this.getDeptManage().equals(other.getDeptManage()))
            && (this.getDeptPhone() == null ? other.getDeptPhone() == null : this.getDeptPhone().equals(other.getDeptPhone()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_basic_dept
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeptName() == null) ? 0 : getDeptName().hashCode());
        result = prime * result + ((getDeptNo() == null) ? 0 : getDeptNo().hashCode());
        result = prime * result + ((getDeptAddress() == null) ? 0 : getDeptAddress().hashCode());
        result = prime * result + ((getDeptManage() == null) ? 0 : getDeptManage().hashCode());
        result = prime * result + ((getDeptPhone() == null) ? 0 : getDeptPhone().hashCode());
        return result;
    }
}