package com.castiel.model.generator;

import com.castiel.core.base.BaseModel;

@SuppressWarnings("serial")
public class PBasicStu extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_stu.STU_NAME
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_stu.DEPT_ID
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_stu.STU_TYPE
     *
     * @mbggenerated
     */
    private Integer stuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_stu.STU_MAJOR
     *
     * @mbggenerated
     */
    private String stuMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_basic_stu.STU_PHONE
     *
     * @mbggenerated
     */
    private String stuPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_stu.STU_NAME
     *
     * @return the value of p_basic_stu.STU_NAME
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_stu.STU_NAME
     *
     * @param stuName the value for p_basic_stu.STU_NAME
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_stu.DEPT_ID
     *
     * @return the value of p_basic_stu.DEPT_ID
     *
     * @mbggenerated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_stu.DEPT_ID
     *
     * @param deptId the value for p_basic_stu.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_stu.STU_TYPE
     *
     * @return the value of p_basic_stu.STU_TYPE
     *
     * @mbggenerated
     */
    public Integer getStuType() {
        return stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_stu.STU_TYPE
     *
     * @param stuType the value for p_basic_stu.STU_TYPE
     *
     * @mbggenerated
     */
    public void setStuType(Integer stuType) {
        this.stuType = stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_stu.STU_MAJOR
     *
     * @return the value of p_basic_stu.STU_MAJOR
     *
     * @mbggenerated
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_stu.STU_MAJOR
     *
     * @param stuMajor the value for p_basic_stu.STU_MAJOR
     *
     * @mbggenerated
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_basic_stu.STU_PHONE
     *
     * @return the value of p_basic_stu.STU_PHONE
     *
     * @mbggenerated
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_basic_stu.STU_PHONE
     *
     * @param stuPhone the value for p_basic_stu.STU_PHONE
     *
     * @mbggenerated
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_basic_stu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuName=").append(stuName);
        sb.append(", deptId=").append(deptId);
        sb.append(", stuType=").append(stuType);
        sb.append(", stuMajor=").append(stuMajor);
        sb.append(", stuPhone=").append(stuPhone);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_basic_stu
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PBasicStu other = (PBasicStu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStuName() == null ? other.getStuName() == null : this.getStuName().equals(other.getStuName()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getStuType() == null ? other.getStuType() == null : this.getStuType().equals(other.getStuType()))
            && (this.getStuMajor() == null ? other.getStuMajor() == null : this.getStuMajor().equals(other.getStuMajor()))
            && (this.getStuPhone() == null ? other.getStuPhone() == null : this.getStuPhone().equals(other.getStuPhone()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_basic_stu
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStuName() == null) ? 0 : getStuName().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getStuType() == null) ? 0 : getStuType().hashCode());
        result = prime * result + ((getStuMajor() == null) ? 0 : getStuMajor().hashCode());
        result = prime * result + ((getStuPhone() == null) ? 0 : getStuPhone().hashCode());
        return result;
    }
}