package com.castiel.model.generator;

import java.util.Date;

import com.castiel.core.base.BaseModel;

@SuppressWarnings("serial")
public class PBasicAct extends BaseModel {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_NAME
	 *
	 * @mbggenerated
	 */
	private String actName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.DEPT_ID
	 *
	 * @mbggenerated
	 */
	private String deptId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_NO
	 *
	 * @mbggenerated
	 */
	private String actNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_ENROL_START_TIME
	 *
	 * @mbggenerated
	 */
	private Date actEnrolStartTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_ENROL_END_TIME
	 *
	 * @mbggenerated
	 */
	private Date actEnrolEndTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_START_TIME
	 *
	 * @mbggenerated
	 */
	private Date actStartTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_END_TIME
	 *
	 * @mbggenerated
	 */
	private Date actEndTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_CONTENT
	 *
	 * @mbggenerated
	 */
	private String actContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_basic_act.ACT_PLACE
	 *
	 * @mbggenerated
	 */
	private String actPlace;

	private Date storageTime;

	private String conType;

	private Date actCancleTime;
	private String actPeopleNumber;
	private String actTeacherNumber;
	private String actStudentNumber;


	public Date getActCancleTime() {
		return actCancleTime;
	}

	public void setActCancleTime(Date actCancleTime) {
		this.actCancleTime = actCancleTime;
	}

	public String getActPeopleNumber() {
		return actPeopleNumber;
	}

	public void setActPeopleNumber(String actPeopleNumber) {
		this.actPeopleNumber = actPeopleNumber;
	}

	public String getActTeacherNumber() {
		return actTeacherNumber;
	}

	public void setActTeacherNumber(String actTeacherNumber) {
		this.actTeacherNumber = actTeacherNumber;
	}

	public String getActStudentNumber() {
		return actStudentNumber;
	}

	public void setActStudentNumber(String actStudentNumber) {
		this.actStudentNumber = actStudentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_NAME
	 *
	 * @return the value of p_basic_act.ACT_NAME
	 *
	 * @mbggenerated
	 */
	public String getActName() {
		return actName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_NAME
	 *
	 * @param actName the value for p_basic_act.ACT_NAME
	 *
	 * @mbggenerated
	 */
	public void setActName(String actName) {
		this.actName = actName == null ? null : actName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.DEPT_ID
	 *
	 * @return the value of p_basic_act.DEPT_ID
	 *
	 * @mbggenerated
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.DEPT_ID
	 *
	 * @param deptId the value for p_basic_act.DEPT_ID
	 *
	 * @mbggenerated
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId == null ? null : deptId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_NO
	 *
	 * @return the value of p_basic_act.ACT_NO
	 *
	 * @mbggenerated
	 */
	public String getActNo() {
		return actNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_NO
	 *
	 * @param actNo the value for p_basic_act.ACT_NO
	 *
	 * @mbggenerated
	 */
	public void setActNo(String actNo) {
		this.actNo = actNo == null ? null : actNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_ENROL_START_TIME
	 *
	 * @return the value of p_basic_act.ACT_ENROL_START_TIME
	 *
	 * @mbggenerated
	 */
	public Date getActEnrolStartTime() {
		return actEnrolStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_ENROL_START_TIME
	 *
	 * @param actEnrolStartTime the value for p_basic_act.ACT_ENROL_START_TIME
	 *
	 * @mbggenerated
	 */
	public void setActEnrolStartTime(Date actEnrolStartTime) {
		this.actEnrolStartTime = actEnrolStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_ENROL_END_TIME
	 *
	 * @return the value of p_basic_act.ACT_ENROL_END_TIME
	 *
	 * @mbggenerated
	 */
	public Date getActEnrolEndTime() {
		return actEnrolEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_ENROL_END_TIME
	 *
	 * @param actEnrolEndTime the value for p_basic_act.ACT_ENROL_END_TIME
	 *
	 * @mbggenerated
	 */
	public void setActEnrolEndTime(Date actEnrolEndTime) {
		this.actEnrolEndTime = actEnrolEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_START_TIME
	 *
	 * @return the value of p_basic_act.ACT_START_TIME
	 *
	 * @mbggenerated
	 */
	public Date getActStartTime() {
		return actStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_START_TIME
	 *
	 * @param actStartTime the value for p_basic_act.ACT_START_TIME
	 *
	 * @mbggenerated
	 */
	public void setActStartTime(Date actStartTime) {
		this.actStartTime = actStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_END_TIME
	 *
	 * @return the value of p_basic_act.ACT_END_TIME
	 *
	 * @mbggenerated
	 */
	public Date getActEndTime() {
		return actEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_END_TIME
	 *
	 * @param actEndTime the value for p_basic_act.ACT_END_TIME
	 *
	 * @mbggenerated
	 */
	public void setActEndTime(Date actEndTime) {
		this.actEndTime = actEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_CONTENT
	 *
	 * @return the value of p_basic_act.ACT_CONTENT
	 *
	 * @mbggenerated
	 */
	public String getActContent() {
		return actContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_CONTENT
	 *
	 * @param actContent the value for p_basic_act.ACT_CONTENT
	 *
	 * @mbggenerated
	 */
	public void setActContent(String actContent) {
		this.actContent = actContent == null ? null : actContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_basic_act.ACT_PLACE
	 *
	 * @return the value of p_basic_act.ACT_PLACE
	 *
	 * @mbggenerated
	 */
	public String getActPlace() {
		return actPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_basic_act.ACT_PLACE
	 *
	 * @param actPlace the value for p_basic_act.ACT_PLACE
	 *
	 * @mbggenerated
	 */
	public void setActPlace(String actPlace) {
		this.actPlace = actPlace == null ? null : actPlace.trim();
	}



	public Date getStorageTime() {
		return storageTime;
	}

	public void setStorageTime(Date storageTime) {
		this.storageTime = storageTime;
	}

	public String getConType() {
		return conType;
	}

	public void setConType(String conType) {
		this.conType = conType;
	}

	@Override
	public String toString() {
		return "PBasicAct [actName=" + actName + ", deptId=" + deptId + ", actNo=" + actNo + ", actEnrolStartTime=" + actEnrolStartTime + ", actEnrolEndTime=" + actEnrolEndTime + ", actStartTime=" + actStartTime + ", actEndTime=" + actEndTime + ", actContent=" + actContent + ", actPlace=" + actPlace + ", storageTime=" + storageTime + ", conType=" + conType + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actContent == null) ? 0 : actContent.hashCode());
		result = prime * result + ((actEndTime == null) ? 0 : actEndTime.hashCode());
		result = prime * result + ((actEnrolEndTime == null) ? 0 : actEnrolEndTime.hashCode());
		result = prime * result + ((actEnrolStartTime == null) ? 0 : actEnrolStartTime.hashCode());
		result = prime * result + ((actName == null) ? 0 : actName.hashCode());
		result = prime * result + ((actNo == null) ? 0 : actNo.hashCode());
		result = prime * result + ((actPlace == null) ? 0 : actPlace.hashCode());
		result = prime * result + ((actStartTime == null) ? 0 : actStartTime.hashCode());
		result = prime * result + ((conType == null) ? 0 : conType.hashCode());
		result = prime * result + ((deptId == null) ? 0 : deptId.hashCode());
		result = prime * result + ((storageTime == null) ? 0 : storageTime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PBasicAct other = (PBasicAct) obj;
		if (actContent == null) {
			if (other.actContent != null)
				return false;
		} else if (!actContent.equals(other.actContent))
			return false;
		if (actEndTime == null) {
			if (other.actEndTime != null)
				return false;
		} else if (!actEndTime.equals(other.actEndTime))
			return false;
		if (actEnrolEndTime == null) {
			if (other.actEnrolEndTime != null)
				return false;
		} else if (!actEnrolEndTime.equals(other.actEnrolEndTime))
			return false;
		if (actEnrolStartTime == null) {
			if (other.actEnrolStartTime != null)
				return false;
		} else if (!actEnrolStartTime.equals(other.actEnrolStartTime))
			return false;
		if (actName == null) {
			if (other.actName != null)
				return false;
		} else if (!actName.equals(other.actName))
			return false;
		if (actNo == null) {
			if (other.actNo != null)
				return false;
		} else if (!actNo.equals(other.actNo))
			return false;
		if (actPlace == null) {
			if (other.actPlace != null)
				return false;
		} else if (!actPlace.equals(other.actPlace))
			return false;
		if (actStartTime == null) {
			if (other.actStartTime != null)
				return false;
		} else if (!actStartTime.equals(other.actStartTime))
			return false;
		if (conType == null) {
			if (other.conType != null)
				return false;
		} else if (!conType.equals(other.conType))
			return false;
		if (deptId == null) {
			if (other.deptId != null)
				return false;
		} else if (!deptId.equals(other.deptId))
			return false;
		if (storageTime == null) {
			if (other.storageTime != null)
				return false;
		} else if (!storageTime.equals(other.storageTime))
			return false;
		return true;
	}


}
