package com.castiel.model.generator;

import java.util.Date;

import com.castiel.core.base.BaseModel;

@SuppressWarnings("serial")
public class PCardFlow extends BaseModel {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.STU_ID
	 *
	 * @mbggenerated
	 */
	private String stuId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.STU_NAME
	 *
	 * @mbggenerated
	 */
	private String stuName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.DEPT_NAME
	 *
	 * @mbggenerated
	 */
	private String deptName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.STU_TYPE
	 *
	 * @mbggenerated
	 */
	private Integer stuType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.ACT_NAME
	 *
	 * @mbggenerated
	 */
	private String actName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.ACT_TIME
	 *
	 * @mbggenerated
	 */
	private Date actTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.ACT_PLACE
	 *
	 * @mbggenerated
	 */
	private String actPlace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.SIGN_TIME
	 *
	 * @mbggenerated
	 */
	private Date signTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.ISVALID
	 *
	 * @mbggenerated
	 */
	private Integer isvalid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.INVALID_REASON
	 *
	 * @mbggenerated
	 */
	private String invalidReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_card_flow.STORAGE_TIME
	 *
	 * @mbggenerated
	 */
	private Date storageTime;


	private String conType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.STU_ID
	 *
	 * @return the value of p_card_flow.STU_ID
	 *
	 * @mbggenerated
	 */
	public String getStuId() {
		return stuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.STU_ID
	 *
	 * @param stuId the value for p_card_flow.STU_ID
	 *
	 * @mbggenerated
	 */
	public void setStuId(String stuId) {
		this.stuId = stuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.STU_NAME
	 *
	 * @return the value of p_card_flow.STU_NAME
	 *
	 * @mbggenerated
	 */
	public String getStuName() {
		return stuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.STU_NAME
	 *
	 * @param stuName the value for p_card_flow.STU_NAME
	 *
	 * @mbggenerated
	 */
	public void setStuName(String stuName) {
		this.stuName = stuName == null ? null : stuName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.DEPT_NAME
	 *
	 * @return the value of p_card_flow.DEPT_NAME
	 *
	 * @mbggenerated
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.DEPT_NAME
	 *
	 * @param deptName the value for p_card_flow.DEPT_NAME
	 *
	 * @mbggenerated
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.STU_TYPE
	 *
	 * @return the value of p_card_flow.STU_TYPE
	 *
	 * @mbggenerated
	 */
	public Integer getStuType() {
		return stuType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.STU_TYPE
	 *
	 * @param stuType the value for p_card_flow.STU_TYPE
	 *
	 * @mbggenerated
	 */
	public void setStuType(Integer stuType) {
		this.stuType = stuType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.ACT_NAME
	 *
	 * @return the value of p_card_flow.ACT_NAME
	 *
	 * @mbggenerated
	 */
	public String getActName() {
		return actName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.ACT_NAME
	 *
	 * @param actName the value for p_card_flow.ACT_NAME
	 *
	 * @mbggenerated
	 */
	public void setActName(String actName) {
		this.actName = actName == null ? null : actName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.ACT_TIME
	 *
	 * @return the value of p_card_flow.ACT_TIME
	 *
	 * @mbggenerated
	 */
	public Date getActTime() {
		return actTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.ACT_TIME
	 *
	 * @param actTime the value for p_card_flow.ACT_TIME
	 *
	 * @mbggenerated
	 */
	public void setActTime(Date actTime) {
		this.actTime = actTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.ACT_PLACE
	 *
	 * @return the value of p_card_flow.ACT_PLACE
	 *
	 * @mbggenerated
	 */
	public String getActPlace() {
		return actPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.ACT_PLACE
	 *
	 * @param actPlace the value for p_card_flow.ACT_PLACE
	 *
	 * @mbggenerated
	 */
	public void setActPlace(String actPlace) {
		this.actPlace = actPlace == null ? null : actPlace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.SIGN_TIME
	 *
	 * @return the value of p_card_flow.SIGN_TIME
	 *
	 * @mbggenerated
	 */
	public Date getSignTime() {
		return signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.SIGN_TIME
	 *
	 * @param signTime the value for p_card_flow.SIGN_TIME
	 *
	 * @mbggenerated
	 */
	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.ISVALID
	 *
	 * @return the value of p_card_flow.ISVALID
	 *
	 * @mbggenerated
	 */
	public Integer getIsvalid() {
		return isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.ISVALID
	 *
	 * @param isvalid the value for p_card_flow.ISVALID
	 *
	 * @mbggenerated
	 */
	public void setIsvalid(Integer isvalid) {
		this.isvalid = isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.INVALID_REASON
	 *
	 * @return the value of p_card_flow.INVALID_REASON
	 *
	 * @mbggenerated
	 */
	public String getInvalidReason() {
		return invalidReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.INVALID_REASON
	 *
	 * @param invalidReason the value for p_card_flow.INVALID_REASON
	 *
	 * @mbggenerated
	 */
	public void setInvalidReason(String invalidReason) {
		this.invalidReason = invalidReason == null ? null : invalidReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_card_flow.STORAGE_TIME
	 *
	 * @return the value of p_card_flow.STORAGE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getStorageTime() {
		return storageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_card_flow.STORAGE_TIME
	 *
	 * @param storageTime the value for p_card_flow.STORAGE_TIME
	 *
	 * @mbggenerated
	 */
	public void setStorageTime(Date storageTime) {
		this.storageTime = storageTime;
	}

	public String getConType() {
		return conType;
	}

	public void setConType(String conType) {
		this.conType = conType;
	}

	@Override
	public String toString() {
		return "PCardFlow [stuId=" + stuId + ", stuName=" + stuName + ", deptName=" + deptName + ", stuType=" + stuType + ", actName=" + actName + ", actTime=" + actTime + ", actPlace=" + actPlace + ", signTime=" + signTime + ", isvalid=" + isvalid + ", invalidReason=" + invalidReason + ", storageTime=" + storageTime + ", conType=" + conType + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actName == null) ? 0 : actName.hashCode());
		result = prime * result + ((actPlace == null) ? 0 : actPlace.hashCode());
		result = prime * result + ((actTime == null) ? 0 : actTime.hashCode());
		result = prime * result + ((conType == null) ? 0 : conType.hashCode());
		result = prime * result + ((deptName == null) ? 0 : deptName.hashCode());
		result = prime * result + ((invalidReason == null) ? 0 : invalidReason.hashCode());
		result = prime * result + ((isvalid == null) ? 0 : isvalid.hashCode());
		result = prime * result + ((signTime == null) ? 0 : signTime.hashCode());
		result = prime * result + ((storageTime == null) ? 0 : storageTime.hashCode());
		result = prime * result + ((stuId == null) ? 0 : stuId.hashCode());
		result = prime * result + ((stuName == null) ? 0 : stuName.hashCode());
		result = prime * result + ((stuType == null) ? 0 : stuType.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PCardFlow other = (PCardFlow) obj;
		if (actName == null) {
			if (other.actName != null)
				return false;
		} else if (!actName.equals(other.actName))
			return false;
		if (actPlace == null) {
			if (other.actPlace != null)
				return false;
		} else if (!actPlace.equals(other.actPlace))
			return false;
		if (actTime == null) {
			if (other.actTime != null)
				return false;
		} else if (!actTime.equals(other.actTime))
			return false;
		if (conType == null) {
			if (other.conType != null)
				return false;
		} else if (!conType.equals(other.conType))
			return false;
		if (deptName == null) {
			if (other.deptName != null)
				return false;
		} else if (!deptName.equals(other.deptName))
			return false;
		if (invalidReason == null) {
			if (other.invalidReason != null)
				return false;
		} else if (!invalidReason.equals(other.invalidReason))
			return false;
		if (isvalid == null) {
			if (other.isvalid != null)
				return false;
		} else if (!isvalid.equals(other.isvalid))
			return false;
		if (signTime == null) {
			if (other.signTime != null)
				return false;
		} else if (!signTime.equals(other.signTime))
			return false;
		if (storageTime == null) {
			if (other.storageTime != null)
				return false;
		} else if (!storageTime.equals(other.storageTime))
			return false;
		if (stuId == null) {
			if (other.stuId != null)
				return false;
		} else if (!stuId.equals(other.stuId))
			return false;
		if (stuName == null) {
			if (other.stuName != null)
				return false;
		} else if (!stuName.equals(other.stuName))
			return false;
		if (stuType == null) {
			if (other.stuType != null)
				return false;
		} else if (!stuType.equals(other.stuType))
			return false;
		return true;
	}



}
