package com.castiel.model.generator;

import java.util.Date;

import com.castiel.core.base.BaseModel;

@SuppressWarnings("serial")
public class PScoreSet extends BaseModel {
	private Integer scoreApplySetValue4;

	public Integer getScoreApplySetValue4() {
		return scoreApplySetValue4;
	}

	public void setScoreApplySetValue4(Integer scoreApplySetValue4) {
		this.scoreApplySetValue4 = scoreApplySetValue4;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_APPLY_ID
	 *
	 * @mbggenerated
	 */
	private String scoreApplyId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_APPLY_SET_VALUE1
	 *
	 * @mbggenerated
	 */
	private Integer scoreApplySetValue1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_APPLY_SET_VALUE2
	 *
	 * @mbggenerated
	 */
	private Integer scoreApplySetValue2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_APPLY_SET_VALUE3
	 *
	 * @mbggenerated
	 */
	private Integer scoreApplySetValue3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_AFFIRM_START_TIME
	 *
	 * @mbggenerated
	 */
	private Date scoreAffirmStartTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_AFFIRM_END_TIME
	 *
	 * @mbggenerated
	 */
	private Date scoreAffirmEndTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_CYCLE_START_TIME
	 *
	 * @mbggenerated
	 */
	private String scoreCycleStartTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * p_score_set.SCORE_CYCLE_END_TIME
	 *
	 * @mbggenerated
	 */
	private String scoreCycleEndTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_APPLY_ID
	 *
	 * @return the value of p_score_set.SCORE_APPLY_ID
	 *
	 * @mbggenerated
	 */
	public String getScoreApplyId() {
		return scoreApplyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_APPLY_ID
	 *
	 * @param scoreApplyId the value for p_score_set.SCORE_APPLY_ID
	 *
	 * @mbggenerated
	 */
	public void setScoreApplyId(String scoreApplyId) {
		this.scoreApplyId = scoreApplyId == null ? null : scoreApplyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_APPLY_SET_VALUE1
	 *
	 * @return the value of p_score_set.SCORE_APPLY_SET_VALUE1
	 *
	 * @mbggenerated
	 */
	public Integer getScoreApplySetValue1() {
		return scoreApplySetValue1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_APPLY_SET_VALUE1
	 *
	 * @param scoreApplySetValue1 the value for p_score_set.SCORE_APPLY_SET_VALUE1
	 *
	 * @mbggenerated
	 */
	public void setScoreApplySetValue1(Integer scoreApplySetValue1) {
		this.scoreApplySetValue1 = scoreApplySetValue1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_APPLY_SET_VALUE2
	 *
	 * @return the value of p_score_set.SCORE_APPLY_SET_VALUE2
	 *
	 * @mbggenerated
	 */
	public Integer getScoreApplySetValue2() {
		return scoreApplySetValue2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_APPLY_SET_VALUE2
	 *
	 * @param scoreApplySetValue2 the value for p_score_set.SCORE_APPLY_SET_VALUE2
	 *
	 * @mbggenerated
	 */
	public void setScoreApplySetValue2(Integer scoreApplySetValue2) {
		this.scoreApplySetValue2 = scoreApplySetValue2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_APPLY_SET_VALUE3
	 *
	 * @return the value of p_score_set.SCORE_APPLY_SET_VALUE3
	 *
	 * @mbggenerated
	 */
	public Integer getScoreApplySetValue3() {
		return scoreApplySetValue3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_APPLY_SET_VALUE3
	 *
	 * @param scoreApplySetValue3 the value for p_score_set.SCORE_APPLY_SET_VALUE3
	 *
	 * @mbggenerated
	 */
	public void setScoreApplySetValue3(Integer scoreApplySetValue3) {
		this.scoreApplySetValue3 = scoreApplySetValue3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_AFFIRM_START_TIME
	 *
	 * @return the value of p_score_set.SCORE_AFFIRM_START_TIME
	 *
	 * @mbggenerated
	 */
	public Date getScoreAffirmStartTime() {
		return scoreAffirmStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_AFFIRM_START_TIME
	 *
	 * @param scoreAffirmStartTime the value for p_score_set.SCORE_AFFIRM_START_TIME
	 *
	 * @mbggenerated
	 */
	public void setScoreAffirmStartTime(Date scoreAffirmStartTime) {
		this.scoreAffirmStartTime = scoreAffirmStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_AFFIRM_END_TIME
	 *
	 * @return the value of p_score_set.SCORE_AFFIRM_END_TIME
	 *
	 * @mbggenerated
	 */
	public Date getScoreAffirmEndTime() {
		return scoreAffirmEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_AFFIRM_END_TIME
	 *
	 * @param scoreAffirmEndTime the value for p_score_set.SCORE_AFFIRM_END_TIME
	 *
	 * @mbggenerated
	 */
	public void setScoreAffirmEndTime(Date scoreAffirmEndTime) {
		this.scoreAffirmEndTime = scoreAffirmEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_CYCLE_START_TIME
	 *
	 * @return the value of p_score_set.SCORE_CYCLE_START_TIME
	 *
	 * @mbggenerated
	 */
	public String getScoreCycleStartTime() {
		return scoreCycleStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_CYCLE_START_TIME
	 *
	 * @param scoreCycleStartTime the value for p_score_set.SCORE_CYCLE_START_TIME
	 *
	 * @mbggenerated
	 */
	public void setScoreCycleStartTime(String scoreCycleStartTime) {
		this.scoreCycleStartTime = scoreCycleStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column p_score_set.SCORE_CYCLE_END_TIME
	 *
	 * @return the value of p_score_set.SCORE_CYCLE_END_TIME
	 *
	 * @mbggenerated
	 */
	public String getScoreCycleEndTime() {
		return scoreCycleEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column p_score_set.SCORE_CYCLE_END_TIME
	 *
	 * @param scoreCycleEndTime the value for p_score_set.SCORE_CYCLE_END_TIME
	 *
	 * @mbggenerated
	 */
	public void setScoreCycleEndTime(String scoreCycleEndTime) {
		this.scoreCycleEndTime = scoreCycleEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * p_score_set
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", scoreApplyId=").append(scoreApplyId);
		sb.append(", scoreApplySetValue1=").append(scoreApplySetValue1);
		sb.append(", scoreApplySetValue2=").append(scoreApplySetValue2);
		sb.append(", scoreApplySetValue3=").append(scoreApplySetValue3);
		sb.append(", scoreApplySetValue4=").append(scoreApplySetValue4);
		sb.append(", scoreAffirmStartTime=").append(scoreAffirmStartTime);
		sb.append(", scoreAffirmEndTime=").append(scoreAffirmEndTime);
		sb.append(", scoreCycleStartTime=").append(scoreCycleStartTime);
		sb.append(", scoreCycleEndTime=").append(scoreCycleEndTime);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * p_score_set
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PScoreSet other = (PScoreSet) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getScoreApplyId() == null ? other.getScoreApplyId() == null : this.getScoreApplyId().equals(other.getScoreApplyId())) && (this.getScoreApplySetValue1() == null ? other.getScoreApplySetValue1() == null : this.getScoreApplySetValue1().equals(other.getScoreApplySetValue1())) && (this.getScoreApplySetValue2() == null ? other.getScoreApplySetValue2() == null : this.getScoreApplySetValue2().equals(other.getScoreApplySetValue2())) && (this.getScoreApplySetValue3() == null ? other.getScoreApplySetValue3() == null : this.getScoreApplySetValue3().equals(other.getScoreApplySetValue3())) && (this.getScoreAffirmStartTime() == null ? other.getScoreAffirmStartTime() == null : this.getScoreAffirmStartTime().equals(other.getScoreAffirmStartTime())) && (this.getScoreAffirmEndTime() == null ? other.getScoreAffirmEndTime() == null : this.getScoreAffirmEndTime().equals(other.getScoreAffirmEndTime()))
				&& (this.getScoreCycleStartTime() == null ? other.getScoreCycleStartTime() == null : this.getScoreCycleStartTime().equals(other.getScoreCycleStartTime())) && (this.getScoreCycleEndTime() == null ? other.getScoreCycleEndTime() == null : this.getScoreCycleEndTime().equals(other.getScoreCycleEndTime())) && this.getScoreApplySetValue4() == null ? other.getScoreApplySetValue4() == null : this.getScoreApplySetValue4().equals(other.getScoreApplySetValue4());
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * p_score_set
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getScoreApplyId() == null) ? 0 : getScoreApplyId().hashCode());
		result = prime * result + ((getScoreApplySetValue1() == null) ? 0 : getScoreApplySetValue1().hashCode());
		result = prime * result + ((getScoreApplySetValue2() == null) ? 0 : getScoreApplySetValue2().hashCode());
		result = prime * result + ((getScoreApplySetValue3() == null) ? 0 : getScoreApplySetValue3().hashCode());
		result = prime * result + ((getScoreApplySetValue4() == null) ? 0 : getScoreApplySetValue4().hashCode());
		result = prime * result + ((getScoreAffirmStartTime() == null) ? 0 : getScoreAffirmStartTime().hashCode());
		result = prime * result + ((getScoreAffirmEndTime() == null) ? 0 : getScoreAffirmEndTime().hashCode());
		result = prime * result + ((getScoreCycleStartTime() == null) ? 0 : getScoreCycleStartTime().hashCode());
		result = prime * result + ((getScoreCycleEndTime() == null) ? 0 : getScoreCycleEndTime().hashCode());
		return result;
	}
}
