package com.castiel.model.generator;

import com.castiel.core.base.BaseModel;
import java.util.Date;

@SuppressWarnings("serial")
public class PScoreApplySet extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_score_apply_set.SCORE_APPLY_ID
     *
     * @mbggenerated
     */
    private String scoreApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_score_apply_set.SCORE_APPLY_START_TIME
     *
     * @mbggenerated
     */
    private Date scoreApplyStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_score_apply_set.SCORE_APPLY_END_TIME
     *
     * @mbggenerated
     */
    private Date scoreApplyEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_score_apply_set.SCORE_APPLY_ID
     *
     * @return the value of p_score_apply_set.SCORE_APPLY_ID
     *
     * @mbggenerated
     */
    public String getScoreApplyId() {
        return scoreApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_score_apply_set.SCORE_APPLY_ID
     *
     * @param scoreApplyId the value for p_score_apply_set.SCORE_APPLY_ID
     *
     * @mbggenerated
     */
    public void setScoreApplyId(String scoreApplyId) {
        this.scoreApplyId = scoreApplyId == null ? null : scoreApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_score_apply_set.SCORE_APPLY_START_TIME
     *
     * @return the value of p_score_apply_set.SCORE_APPLY_START_TIME
     *
     * @mbggenerated
     */
    public Date getScoreApplyStartTime() {
        return scoreApplyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_score_apply_set.SCORE_APPLY_START_TIME
     *
     * @param scoreApplyStartTime the value for p_score_apply_set.SCORE_APPLY_START_TIME
     *
     * @mbggenerated
     */
    public void setScoreApplyStartTime(Date scoreApplyStartTime) {
        this.scoreApplyStartTime = scoreApplyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_score_apply_set.SCORE_APPLY_END_TIME
     *
     * @return the value of p_score_apply_set.SCORE_APPLY_END_TIME
     *
     * @mbggenerated
     */
    public Date getScoreApplyEndTime() {
        return scoreApplyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_score_apply_set.SCORE_APPLY_END_TIME
     *
     * @param scoreApplyEndTime the value for p_score_apply_set.SCORE_APPLY_END_TIME
     *
     * @mbggenerated
     */
    public void setScoreApplyEndTime(Date scoreApplyEndTime) {
        this.scoreApplyEndTime = scoreApplyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_score_apply_set
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scoreApplyId=").append(scoreApplyId);
        sb.append(", scoreApplyStartTime=").append(scoreApplyStartTime);
        sb.append(", scoreApplyEndTime=").append(scoreApplyEndTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_score_apply_set
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PScoreApplySet other = (PScoreApplySet) that;
        return (this.getScoreApplyId() == null ? other.getScoreApplyId() == null : this.getScoreApplyId().equals(other.getScoreApplyId()))
            && (this.getScoreApplyStartTime() == null ? other.getScoreApplyStartTime() == null : this.getScoreApplyStartTime().equals(other.getScoreApplyStartTime()))
            && (this.getScoreApplyEndTime() == null ? other.getScoreApplyEndTime() == null : this.getScoreApplyEndTime().equals(other.getScoreApplyEndTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_score_apply_set
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getScoreApplyId() == null) ? 0 : getScoreApplyId().hashCode());
        result = prime * result + ((getScoreApplyStartTime() == null) ? 0 : getScoreApplyStartTime().hashCode());
        result = prime * result + ((getScoreApplyEndTime() == null) ? 0 : getScoreApplyEndTime().hashCode());
        return result;
    }
}